// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RLH.Plume.Context;

#nullable disable

namespace RLH.Plume.Migrations
{
    [DbContext(typeof(PlumeContext))]
    [Migration("20220627175615_removeFK")]
    partial class removeFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RLH.Plume.Entities.Measurement", b =>
                {
                    b.Property<string>("Timestamp")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("DateTimeUTC")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("NO2")
                        .HasColumnType("float");

                    b.Property<double>("NO2_AQI")
                        .HasColumnType("float");

                    b.Property<double>("PM01")
                        .HasColumnType("float");

                    b.Property<double>("PM01_AQI")
                        .HasColumnType("float");

                    b.Property<double>("PM10")
                        .HasColumnType("float");

                    b.Property<double>("PM10_AQI")
                        .HasColumnType("float");

                    b.Property<double>("PM25")
                        .HasColumnType("float");

                    b.Property<double>("PM25_AQI")
                        .HasColumnType("float");

                    b.Property<double>("VOC")
                        .HasColumnType("float");

                    b.Property<double>("VOC_AQI")
                        .HasColumnType("float");

                    b.HasKey("Timestamp");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("RLH.Plume.Entities.Position", b =>
                {
                    b.Property<string>("Timestamp")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.HasKey("Timestamp");

                    b.ToTable("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
